/** Integration source badges for case workspace sections. */

function GmailIcon({ size = 24 }: { size?: number }) {
  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      className="gmail-icon"
      src="/brand/gmail.svg"
      alt=""
      width={size}
      height={size}
    />
  );
}

export function GmailMark({ compact = false }: { compact?: boolean }) {
  return (
    <span
      className={`source-badge gmail${compact ? " compact" : ""}`}
      title="Received via Gmail"
    >
      <GmailIcon size={14} />
      {!compact ? <span>GMAIL</span> : null}
    </span>
  );
}

export function AiDraftMark({ compact = false }: { compact?: boolean }) {
  return (
    <span
      className={`source-badge ai${compact ? " compact" : ""}`}
      title="Generated by OpsDesk AI · grounded by policy"
    >
      <svg width="12" height="12" viewBox="0 0 24 24" aria-hidden="true">
        <path
          fill="currentColor"
          d="M12 2.2l1.7 5.5 5.6.2-4.4 3.5 1.5 5.5L12 13.8 7.6 16.9l1.5-5.5L4.7 7.9l5.6-.2L12 2.2z"
        />
      </svg>
      {!compact ? <span>AI draft</span> : null}
    </span>
  );
}

function HubSpotIcon({ size = 20 }: { size?: number }) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 64 64"
      aria-hidden="true"
      focusable="false"
    >
      <circle cx="34" cy="36" r="12" fill="none" stroke="#FF7A59" strokeWidth="7" />
      <line
        x1="34"
        y1="24"
        x2="34"
        y2="12"
        stroke="#FF7A59"
        strokeWidth="5.5"
        strokeLinecap="round"
      />
      <circle cx="34" cy="9" r="5.5" fill="#FF7A59" />
      <line
        x1="24.5"
        y1="29"
        x2="14"
        y2="18.5"
        stroke="#FF7A59"
        strokeWidth="5.5"
        strokeLinecap="round"
      />
      <circle cx="11.5" cy="16" r="5.5" fill="#FF7A59" />
      <line
        x1="24.5"
        y1="43"
        x2="14"
        y2="50.5"
        stroke="#FF7A59"
        strokeWidth="5.5"
        strokeLinecap="round"
      />
      <circle cx="11.5" cy="53" r="5.5" fill="#FF7A59" />
    </svg>
  );
}

export function HubSpotContextBadge() {
  return (
    <div className="context-source-badge hubspot" title="Resident matched in HubSpot CRM">
      <HubSpotIcon size={28} />
      <span className="context-source-name">HubSpot</span>
      <span className="context-source-caption">CRM match</span>
    </div>
  );
}

export function OpsDeskContextBadge() {
  return (
    <div className="context-source-badge local" title="Resident matched in OpsDesk records">
      <span className="context-source-mark" aria-hidden="true">
        Q
      </span>
      <span className="context-source-name">OpsDesk</span>
      <span className="context-source-caption">Local match</span>
    </div>
  );
}

export function NoMatchContextBadge() {
  return (
    <div className="context-source-badge empty" title="No CRM match for this sender">
      <span className="context-source-mark muted-mark" aria-hidden="true">
        —
      </span>
      <span className="context-source-name">No match</span>
      <span className="context-source-caption">CRM lookup</span>
    </div>
  );
}
